### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Thinalraj** [Orabig/Rasp-T6963C#2]
Dear developer, we are facing some errors in compiling your code ? Can you kindly provide us feedback for the error ?

/usr/bin/ld: lcd_register.o: in function `reg_shift':
/home/pi/RaspT6963/src/lcd_register.c:25: undefined reference to `gpio_put'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_register.c:27: undefined reference to `gpio_set'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_register.c:28: undefined reference to `gpio_clr'
/usr/bin/ld: lcd_register.o: in function `reg_data':
/home/pi/RaspT6963/src/lcd_register.c:39: undefined reference to `gpio_set'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_register.c:40: undefined reference to `gpio_clr'
/usr/bin/ld: lcd_register.o: in function `reg_setup':
/home/pi/RaspT6963/src/lcd_register.c:53: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_register.c:54: undefined reference to `gpio_clr'
/usr/bin/ld: lcd_command.o: in function `LCD_setup':
/home/pi/RaspT6963/src/lcd_command.c:50: undefined reference to `gpio_set'
/usr/bin/ld: lcd_command.o: in function `LCD_command':
/home/pi/RaspT6963/src/lcd_command.c:55: undefined reference to `gpio_set'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:57: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:59: undefined reference to `gpio_set'
/usr/bin/ld: lcd_command.o: in function `LCD_data':
/home/pi/RaspT6963/src/lcd_command.c:64: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:66: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:68: undefined reference to `gpio_set'
/usr/bin/ld: lcd_command.o: in function `LCD_Reverse':
/home/pi/RaspT6963/src/lcd_command.c:84: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:86: undefined reference to `gpio_set'
/usr/bin/ld: lcd_command.o: in function `LCD_FontSelect':
/home/pi/RaspT6963/src/lcd_command.c:92: undefined reference to `gpio_clr'
/usr/bin/ld: /home/pi/RaspT6963/src/lcd_command.c:94: undefined reference to `gpio_set'
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: prog] Error 1

I ran make command in src folder.

**Comment by Orabig** [comment]
Hi, you're right.

I've just fixed the code, so that it can be compiled with more modern compilers that the ones I used at that time.

Just update to latest version, it should be ok.
